version: "3.7"
services:
  n1_hello:
    build: .
    stdin_open: true
    tty: true
    networks:
      - simple-network
    volumes:
      - hello_volume:/usr/share/hello
  n2_hello:
    build: .
    stdin_open: true
    tty: true
    networks:
      - simple-network
networks:
  simple-network:
    driver: bridge
volumes:
  hello_volume: